import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
/*
 * AudioEncryption.java
 *
 * Created on 10 December, 2013, 10:21 PM
 */

/**
 *
 * @author  ASHWIN
 *
 */

    	
    


public class AudioEncryption extends javax.swing.JFrame {
    InputStream ins;
            int c=0,n=0,j,i=0,m=0,cou=0,tln=0,tn=1,k=0,t=0,coun=0,pb=0,thr=0,h=0,strl=0,hel=0,inr=0;
	String str="",cr="",sam="";
        String address,form=".wav";
       
    /** Creates new form AudioEncryption */
    public AudioEncryption(){
        /** to put frame in center of screen **/
         setTitle("AUDIO ENCRYPTION");
           // setContentPane(new JLabel(new ImageIcon("STEGO/Tech.jpg")));
            Toolkit toolkit = getToolkit();
            Dimension size = toolkit.getScreenSize();
            setLocation(size.width/3-getWidth()/3,size.height/5-getHeight()/5);
            
    initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        txtFile = new javax.swing.JTextField();
        txtTarget = new javax.swing.JTextField();
        txtKey = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnEncrypt = new javax.swing.JButton();
        btnMainmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("AUDIO ENCRYPTION");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Browse File :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Target File :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Secret Key :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Message :");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        btnEncrypt.setText("Encrypt");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        btnMainmenu.setText("Back");
        btnMainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtKey)
                                            .addComponent(txtTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1)
                                            .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEncrypt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                        .addComponent(btnMainmenu)
                                        .addGap(19, 19, 19)))))
                        .addComponent(btnBrowse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnBrowse)
                    .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncrypt)
                    .addComponent(btnMainmenu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainmenuActionPerformed
// TODO add your handling code here:
         new MainPage().show();
        this.hide();
    }//GEN-LAST:event_btnMainmenuActionPerformed

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed

// TODO add your handling code here:
        if(txtFile.getText().equalsIgnoreCase(txtTarget.getText()))
        {
            JOptionPane.showMessageDialog(this,"Target and source file found same. Please change th value");
        }
        else
        {
                try
	{
	InputStream ints=new FileInputStream(txtFile.getText());
	while(c!=-1)
	{
		c=ints.read();
		if((c==254)||(c==255))
			t++;
		if(t==(strl*8))
		{
			t=0;
			ints.close();
			break;

		}
	}
	ints.close();

	}catch(Exception e){}
	inr=t;
	if(t!=0)
	JOptionPane.showMessageDialog(this,"The Audio file size is too small to encode.Change audio file or reduce the message","ERROR",JOptionPane.ERROR_MESSAGE);
	else
	{
	t=0;
	c=0;
	BigInteger bi1,bi2;
	BigDecimal bd1;
	str=txtKey.getText();
	tln=str.length();
	System.out.println("\n"+"Total No. of characters : "+tln);
	for(int i=0;i<tln;i++)
	{
		tn=(int)str.charAt(i);
		t=t ^ tn;
	}
	t=t>>1;	
	System.out.println("\n"+"Encrypt key :"+t);
	str=txtTarget.getText();
	strl=txtMessage.getText().length();
	int leng=str.length();
	StringBuffer sbr=new StringBuffer(str);
	form=form.toLowerCase();
	if(str.endsWith(""))
	{}
	else if(str.endsWith("jpg")||str.endsWith("jpeg")||str.endsWith("aif")||str.endsWith("mid")||str.endsWith("au"))
	{
		if(str.endsWith(form)){}
		else
		{
			form="."+form;
			sbr.append(form);
			sbr.replace(leng-4,leng,form);
			str=sbr.toString();
			txtTarget.setText(str);
		}
	}
	else
	{
		form="."+form;
		sbr.append(form);
		str=sbr.toString();
		txtTarget.setText(str);
	}

	int a;
	cou=0;
	k=0;
a=JOptionPane.showConfirmDialog(this,"Do u Want To Continue With The Following Information ?","CONFIRM",JOptionPane.YES_NO_OPTION);
	if(a==0)
	{
	
	try
	{
	
	ins=new FileInputStream(txtFile.getText());
	OutputStream outs=new FileOutputStream(txtTarget.getText());
	
	cr=txtMessage.getText();
	tln=cr.length();
				
do
{
            while(tln!=0)
	{
		int as=(int)cr.charAt(cou);
		System.out.println("\n"+"BEFORE ENCRYPTION : "+as);
		as=as+t;
		System.out.println("\n"+"AFTER ENCRYPTION : "+as);
		BigDecimal bc=new BigDecimal(as);
		BigInteger bi=bc.toBigInteger();
		String bn=bi.toString(2);
		coun=8-(bn.length());
		while(coun!=0)
		{
			bn="0"+""+bn;
			coun--;
		}
		
		System.out.println(bn);
	
		tn=bn.length()-1;
			inr=0;		
		do	
		{
			c=ins.read();
			inr++;
			//progressBar.setValue(inr);
			
			if((c==254)||(c==255))
			{
				
					m=0;
					BigDecimal bd=new BigDecimal(c);
				        BigInteger Bn=bd.toBigInteger();
					String slen=Bn.toString(2);
					System.out.println("\n"+c);
					System.out.println("BIT PATTERN BEFORE ENCODING : "+slen);
					StringBuffer sb=new StringBuffer(slen);
					sb.deleteCharAt(sb.length()-1);
					str=sb+""+bn.charAt(tn);
					System.out.println("BIT PATTERN AFTER ENCODING:"+str);
					int len=str.length()-1;
					
					for(i=len;i>=0;i--)
					{
						k=k+1;
						Character cs=new Character(str.charAt(i));
						String sr=cs.toString();
						n=Integer.parseInt(sr);
						for(j=0;j<k;j++)
						{
							if(j!=0)
								n=n*2;
						}
			
						m=m+n;
					}
				
				
				outs.write(m);
				
				tn=tn-1;
				k=0;
				
			}
			
			else
			outs.write(c);
			
		            
		}while(tn>=0);
		
		tln=tln-1;
		cou=cou+1;
	}	
		
		c=ins.read();
		inr++;
//		progressBar.setValue(inr);
		if((c==254)||(c==255))
		{
		if(coun!=8)
		{
		outs.write(255);
		coun++;
		}
		else
		outs.write(c);
		}
		else
		outs.write(c);
			
	
		
}while(c!=-1);

ins.close();
outs.close();

JOptionPane.showMessageDialog(this,"The Message is successfully Encoded in the File","INFORM",JOptionPane.INFORMATION_MESSAGE);

}
catch(Exception e){
JOptionPane.showMessageDialog(this,e,"ERROR",JOptionPane.ERROR_MESSAGE);
}
        }
        }
        }                                        

    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
// TODO add your handling code here:
         JFileChooser filechooser=new JFileChooser(JFileChooser.SELECTED_FILES_CHANGED_PROPERTY);
	File f=new File("\\Sample_Audios\\");
	filechooser.setCurrentDirectory(f);
	filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
	//filechooser.setFileFilter(new filter());
	String se="";
	int r=filechooser.showOpenDialog(this);
	File fc=filechooser.getCurrentDirectory();
				
	File tempfilename=filechooser.getSelectedFile(); 
	
      	if(r==JFileChooser.CANCEL_OPTION)
	       JOptionPane.showMessageDialog(this,"File Not Selected","Error",JOptionPane.ERROR_MESSAGE);	
      	else
        		se=""+fc+"\\"+tempfilename.getName();
	int ind=se.indexOf('\\',3);
	
	if(ind==3)
	{
	StringBuffer sbu= new StringBuffer(se);
	sbu.deleteCharAt(ind);
	se=sbu.toString();
	}
		
	txtFile.setText(se);
        txtTarget.setText(se);
    
    }//GEN-LAST:event_btnBrowseActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()  {
                new AudioEncryption().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JButton btnMainmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtTarget;
    // End of variables declaration//GEN-END:variables

    
}
